Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

# Use your best judgement please
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Layout/AlignParameters:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/IndentArray:
  Enabled: false

# Test only excludes
Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
